### ISSUE TITLE
yaml bugged

### ISSUE THREAD

**Issue by chocolatederp** [T0r1nn/APLC#5]
the default yaml has a thing at line 419 where it says ":50" by default, which leads to it being broken. if its replaced with "false:50" it works, updating the default yaml to say "false:50" for the custom content would fix this

**Comment by T0r1nn** [comment]
I goofed, that option doesnt do anything yet and shouldn't have been on the yaml. I'll fix it today

**Comment by T0r1nn** [comment]
Fixed, thank you for the report
